jobs:
  publish:
    name: Publish tinylog ${{github.event.inputs.version}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure GIT
      run: 'git config --global user.name "${{github.actor}}"

        git config --global user.email "${{github.actor}}@users.noreply.github.com"

        '
    - continue-on-error: true
      name: Check out tinylog repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 9
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 9
    - continue-on-error: true
      name: Store original version
      run: 'echo "ORIGINAL_VERSION=$(mvn help:evaluate -Dexpression=project.version
        -q -DforceStdout)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Create version ${{github.event.inputs.version}}
      run: 'mvn -DnewVersion=${{github.event.inputs.version}} -DgenerateBackupPoms=false
        --no-transfer-progress --batch-mode versions:set

        git commit -am "Release version ${{github.event.inputs.version}}"

        git tag "${{github.event.inputs.version}}"

        '
    - continue-on-error: true
      name: Deploy version ${{github.event.inputs.version}}
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_passphrase: ${{secrets.OSSRH_GPG_PASSWORD}}
        gpg_private_key: ${{secrets.OSSRH_GPG_SECRET_KEY}}
        maven_args: --no-transfer-progress --batch-mode
        maven_profiles: release
        nexus_password: ${{secrets.OSSRH_SERVER_PASSWORD}}
        nexus_username: pmw
    - continue-on-error: true
      name: Create P2 repository
      run: 'mvn -P release --no-transfer-progress --batch-mode --non-recursive p2:site

        '
    - continue-on-error: true
      name: Upload P2 repository
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        dist_target_dir: ${{github.event.inputs.version}}
        ftp_host: tinylog.org
        ftp_password: ${{secrets.FTP_PASSWORD_TINYLOG2_P2_REPOSITORY}}
        ftp_username: tinylog2-p2-repository@tinylog.org
        local_source_dir: target/repository
    - continue-on-error: true
      name: Create release draft
      uses: ncipollo/release-action@v1
      with:
        artifacts: target/*
        draft: true
        name: Version ${{github.event.inputs.version}}
        prerelease: ${{contains(github.event.inputs.version, '-')}}
        tag: ${{github.event.inputs.version}}
        token: ${{secrets.GITHUB_TOKEN}}
    - continue-on-error: true
      name: Store file size
      run: 'FILE_PATH_API=tinylog-api/target/tinylog-api-${{github.event.inputs.version}}.jar

        FILE_SIZE_API=$(stat -c%s "$FILE_PATH_API")

        FILE_PATH_IMPL=tinylog-impl/target/tinylog-impl-${{github.event.inputs.version}}.jar

        FILE_SIZE_IMPL=$(stat -c%s "$FILE_PATH_IMPL")

        echo "FILE_SIZE=$((FILE_SIZE_API + FILE_SIZE_IMPL))" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Restore original version
      run: 'mvn -DnewVersion=${ORIGINAL_VERSION} -DgenerateBackupPoms=false --no-transfer-progress
        --batch-mode versions:set

        git commit -am "Restore snapshot version ${ORIGINAL_VERSION}"

        '
    - continue-on-error: true
      name: Push changes to tinylog repository
      run: 'git push origin

        git push origin "${{github.event.inputs.version}}"

        '
name: Publish New Version
on:
  repository_dispatch:
    types: trigger-ga___publish.yaml
